all:
  children:
    prodgeek:
      hosts:
        vagrant1:
          ansible_ssh_host: 192.168.56.11
          ansible_ssh_port: 22
        vagrant2:
          ansible_ssh_host: 192.168.56.12
          ansible_ssh_port: 22
        vagrant3:
          ansible_ssh_host: 192.168.56.13
          ansible_ssh_port: 22
        vagrant4:
          ansible_ssh_host: 192.168.56.14
          ansible_ssh_port: 22